// Code generated by mockery v1.0.0. DO NOT EDIT.
package copycat

import mock "github.com/stretchr/testify/mock"
import raftpb "github.com/coreos/etcd/raft/raftpb"

// mockRaftTransport is an autogenerated mock type for the raftTransport type
type mockRaftTransport struct {
	mock.Mock
}

// sendMessages provides a mock function with given fields: msgs
func (_m *mockRaftTransport) sendMessages(msgs []raftpb.Message) *messageSendingResults {
	ret := _m.Called(msgs)

	var r0 *messageSendingResults
	if rf, ok := ret.Get(0).(func([]raftpb.Message) *messageSendingResults); ok {
		r0 = rf(msgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messageSendingResults)
		}
	}

	return r0
}
